# General parameters
random_seed: 13
n_jobs: 1
overwrite: True
verbose: True

# Model training parameters
downsampling: !!null
trained_model_path: './results/tsadams/trained_models'
dataset_path: './data/autotsad-data'
min_length: 256
training_size: 1
model_architectures: 'all'

# Model evaluation parameters
normalize: True
results_path: './results/tsadams/results'
n_repeats: 2
split: 'test'
synthetic_ranking_criterion: 'f1'
n_splits: 100
n_validation_splits: 5
n_neighbors: [2, 4, 6]
evaluation_metric: 'Best F-1'
sliding_window: !!null
metric: 'influence'
top_k: 3
use_all_ranks: False
top_kr: !!null
