[connections.autotsad]
url = "postgresql+psycopg2://<user>:<pw>@<host>:<port>/<database>"
# SSH-Proxy to connect to DB on amalia (uses existing SSH-Proxy configuration for amalia):
# ssh -L 5432:amalia:5432 amalia@amalia

ttl = 3600
persist_cache = true

[connections.autotsad.create_engine_kwargs.connect_args]
isolation_level = "SERIALIZABLE"
